# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1waKrxZWdB3HeN5kOCDKpG3cHB8RKG0sw
"""

#1
length = float(input("Enter the length: "))
width = float(input("Enter the width: "))
area = length * width
print(f"The area of the rectangle is {area}")

#2
weight = float(input("Enter your weight (in kg): "))
height = float(input("Enter your height (in m): "))
bmi = (weight)/(height**2)
print(f"Your BMI is {bmi}")

#3
dictionary = {"Siva": 98, "Selva": 95,"Harish": 99, "Sushil": 100}
print(dictionary)

#4
age = int(input("Enter your age: "))
if(age <18):
  print("minor")
elif(age >=18 and age<=30):
  print("adult")
else:
  print("senior")

#5
for i in range(1,51):
  if(i%2==0):
    print(i,end=" ")

#6
while True:
  correct_password = "viratkohli18"
  password = input("Enter your password: ")
  if(correct_password != password):
    continue
  else:
    print("Your password is right!")
    break

#7
def average_list_of_numbers(l):
  total_sum=0
  for i in l:
    total_sum+=i
  avg = total_sum/ len(l)
  return avg
l=[1,2,3,4,5]
average_list_of_numbers(l)

#8
def vowels(name):
  vowels= ['a','e','i','o','u','A','E','I','O','U']
  count=0
  for i in name:
    if(i in vowels):
      count +=1
  return count

name = input("Enter your name: ")
print(f"Vowels: {vowels(name)}")

#9
from datetime import datetime
current_date= datetime.now()
print(current_date)

#10
try:
  values=[1,2,3,'a','b']
  total_sum = 0
  for i in values:
    total_sum+=i
  print(total_sum)
except TypeError:
  print("Type error")

#11
try:
  a =[1,2,3,4,5]
  x,y,z = a
  print(x)
except ValueError:
  print("Value Error happened")

#12
try:
  a=15
  b=0
  c=a/b
  print(c)
except ZeroDivisionError:
  print("Cannot divide by zero")

#13
file_path = "new_file.txt"
with open(file_path, 'w') as file:
    file.write("Hello, Python!")
print(f"File '{file_path}' created successfully.")

#14
file_path = 'new_file.txt'
with open(file_path, 'r') as file:
    file_contents = file.read()
    print(file_contents)

#15
f = open('new_file.txt','a')
f.writelines('Good to see you here')
f = open('new_file.txt','r')
f.readlines()